language: cpp

compiler:
  - clang

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4
      
script: 
  - make

after_success:
  - make dotmark32

